### ISSUE TITLE
Blocker for using 0.9.x

### ISSUE THREAD

**Issue by alexsomesan** [coreos/terraform#2]
Due to https://github.com/hashicorp/terraform/issues/11518 we're blocked on upgrading to 0.9.x

The issue is transient but prevents a build from succeeding on the first attempt.
A second apply will build correctly.
This is not desirable behaviour and we should hold off upgrading until above upstream issue is resolved.

@Quentin-M @s-urbaniak

**Comment by Quentin-M** [comment]
Thanks for filing!
